### ISSUE TITLE
Xbox crash on startup

### ISSUE THREAD

**Issue by COM8** [UWPX/UWPX-Client#169]
Hello!
Sadly Uwpx does not work in my Xbox anymore :/
It crashes on startup, no idea if you can see it on application insights

_Originally posted by @LAGonauta in https://github.com/UWPX/UWPX-Client/issues/48#issuecomment-1030705015_

**Comment by COM8** [comment]
I tried to reproduce this on an Xbox S and was not successful with it.
I fixed some more cases this behavior could be caused by. Hope to push them out in the next release soon.
If those don't help, my last guess would be that it's related to your or your contacts avatar since I still find a couple of edge cases where downloading them crashes the app in case they are malformed.

**Comment by LAGonauta** [comment]
Still unable to load it, however UWPX is connecting and I am receiving notifications. It just doesn't load the interface. 
Maybe it is crashing in some native code, and that is why you are not receiving the crash log?

I will try it in a Windows PC again, maybe it is crashing with my account there too.

**Comment by COM8** [comment]
Interesting. On the weekend I will have time to dive deeper into this again and see if there are any crash reports this time that made it.

**Comment by COM8** [comment]
@LAGonauta Did you have a chance to check it on your PC?

**Comment by LAGonauta** [comment]
Just did, actually.
It doesn't crash, but I do receive thousands of notifications (a notification flood). Every message from MAM, it seems.
Could that be it? Maybe the notification system in the XBox is not able to cope for some reason? 🤔

**Comment by LAGonauta** [comment]
OK, it did end up freezing and crashing my task bar after some minutes.

**Comment by COM8** [comment]
I released a new version of UWPX with a new way to report crashes. This should be more reliable!
https://github.com/UWPX/UWPX-Client/releases/tag/v.0.41.0.0

**Comment by LAGonauta** [comment]
I sent you some crash reports yesterday 👍
However I forgot to send one... The stack trace said the the ChatMessages table did not exist. I guess the database got corrupted with all other crashes and the app wasn't able to recover.

**Comment by COM8** [comment]
Fixed it hopefully! A new release will be out shortly.

**Comment by COM8** [comment]
https://github.com/UWPX/UWPX-Client/releases/tag/v.0.41.6.0
